language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: i008
  password:
    secure: FNtfh6S0C0KHgTzRfhpPQ07lD+5VLmI8uWlvJeTf3S5HseMLtZzxxkFvkNFAYggxMWCYCATzvWFte8QcyYcYcXvd2eUIEVTP8ZarTwe/Eda6opf43dv5Hn6Eq6ZwGyipALYHmLSHz96pySYaV4AKGrQSf54Jcy4hTBDk6yxTPDLwna8Sky6MeQ1FXlqZ+WOdY79Vit6uaLYf/PuWLpnmCVLc74CqXbdMYrvxamkt48yHbA8jNV9TfyMcsltpG+gLZBR0yxuYW/OE1R/RNhle+kR1g5maMTkBdQ3Qgynyjkan1QAmdlUtkefMeBZ2o4foaeVVbp94vZKv8zoZdP64mg+wvrxZxju5fOoLqnVpa3gQnpD9TYKVrSEe1szIMP/FACVUx249K10kmGUCAwT1x7r/q5rZFEP5HdqoNlpyyeCq1v2TH6Modsw6C/RBgUCE3uiMyp8g1x2iNy1la3wFbMqZMu9GExIMrVO6086sbF1wIXkXWu+rbtXbYVVzwjvqqufp/skCUDvKaLasI89hOc/GoSlYvkQHSfygT6VGpKJqd+zZvZ2l2pBepTrP/HuiWlcf+Wrp035i1kXd/lbxtU3lByLeH+1gX9//nckURKyvuMs0oTcAbD9qjskue4xMKNDnHQMiWowtuhZ0kyNnUJVX5QlRLeJfBaLhN6f30Ao=
  on:
    tags: true
    repo: i008/clean_ipynb
    python: 3.6
